const { Router } = require('express');
const app = Router();
let games = [
    { id: 1, title: "187 Ride of Die", Developers: 'Ubisoft Paris', Publishers: 'Ubisoft', Pal: 'Aug 25 2025', JP: 'Unrelased', NA: 'Aug 23 2005', Genre: 'arcade racing' },
    { id: 2, title: '2002 Fifa World Cup', Developers: 'EA Canada, Creations, Intelligent Games', Publishers: 'EA Sports(WorldWide), Electronic Arts Sqaure(Japan)', Pal: 'Apr 26 2002', JP: 'May 2 2002', Na: 'Apr 22 2002', Genre: 'Sports' },
    { id: 3, title: '2006 Fifa World Cup', Developers: 'EA Canada', Publishers: 'EA Sports', Pal: 'Apr 26 2002', JP: 'Unrelased', Na: 'Apr 22 2002', Genre: 'Sports' },
    { id: 4, title: '25 to Life', Developers: 'Avalanche Software Ritual Entertainment', Publishers: 'Eidos Interactive', Pal: 'Unrelased', JP: 'Unrelased', Na: 'Apr 24 2006', Genre: 'Third-person shooter' },
    { id: 5, title: '4x4 Evo 2', Developers: 'Terminal Reality', Publishers: 'Gathering Of Developers', Pal: 'Jun 5 2002', JP: 'Unrelased', Na: 'Nov 15 2001', Genre: 'racing simulation' },
    { id: 6, title: "50 Cent: Bulletproof", Developers: "Genuine Games", Publishers: "Vivendi Universal Games", Pal: "Nov 25, 2005", JP: "Unreleased", NA: "Nov 17, 2005", Genre: 'Third-person shooter' },
    { id: 7, title: "Advent Rising", Developers: "GlyphX Games", Publishers: "Majesco Entertainment", Pal: "Feb 17, 2006", JP: "Unreleased", NA: "May 31, 2005", Genre: 'Action-adventure' },
    { id: 8, title: "Æon Flux", Developers: "Terminal Reality", Publishers: "Majesco Entertainment", Pal: "Mar 30, 2006AUS Mar 31, 2006", JP: "Unreleased", NA: "Nov 15, 2005", Genre: 'science-fiction' },
    { id: 9, title: "AFL Live 2003", Developers: "IR Gurus", Publishers: "Acclaim Sports", Pal: "Sep 5, 2002AUS", JP: "Unreleased", NA: "Unreleased", Genre: 'sports simulation' },
    { id: 10, title: "AFL Live 2004", Developers: "IR Gurus", Publishers: "Acclaim Entertainment", Pal: "Aug 28, 2003AUS", JP: "Unreleased", NA: "Unreleased", Genre: 'sports simulation' },
    { id: 11, title: "AFL Live: Premiership Edition", Developers: "IR Gurus", Publishers: "Acclaim Entertainment THQ", Pal: "Apr 29, 2004AUS", JP: "Unreleased", NA: "Unreleased", Genre: 'sports simulation' },
    { id: 12, title: "AFL Premiership", Developers: "IR Gurus", Publishers: "THQ", Pal: "Sep 22, 2005", JP: "Unreleased", NA: "Unreleased", Genre: 'sports simulation' },
    { id: 13, title: "Aggressive Inline", Developers: "Z-Axis", Publishers: "AKA Acclaim", Pal: "Aug 23, 2002", JP: "Unreleased", NA: "Aug 1, 2002", Genre: 'sports simulation' },
    { id: 14, title: "AirForce Delta StormDeadly Skies (PAL)Airforce Delta II (JP)", Developers: "Konami Computer Entertainment Studios", Publishers: "Konami", Pal: "Apr 12, 2002", JP: "Feb 22, 2002", NA: "Nov 15, 2001", Genre: 'combat flight simulation' },
    { id: 15, title: "Alias", Developers: "Acclaim Studios Cheltenham", Publishers: "Acclaim Entertainment", Pal: "Apr 8, 2004", JP: "Unreleased", NA: "Apr 6, 2004", Genre: '3D third-person action-adventure/stealth video game' },
    { id: 16, title: "Alien Hominid", Developers: "The Behemoth", Publishers: "Zoo Digital Publishing", Pal: "May 27, 2005", JP: "Unreleased", NA: "Unreleased", Genre: 'Run and gun' },
    { id: 17, title: "Aliens Versus Predator: Extinction", Developers: "Zono", Publishers: "Electronic Arts", Pal: "Aug 8, 2003", JP: "Unreleased", NA: "Aug 5, 2003", Genre: 'Real-time strategy' },
    { id: 18, title: "All-Star Baseball 2003", Developers: "Acclaim Studios Austin", Publishers: "Acclaim Sports", Pal: "May 31, 2002", JP: "Aug 8, 2002", NA: "Mar 7, 2002", Genre: 'Sports game' },
    { id: 19, title: "All-Star Baseball 2004", Developers: "Acclaim Studios Austin", Publishers: "Acclaim Sports", Pal: "Unreleased", JP: "Unreleased", NA: "Feb 28, 2003", Genre: 'Sports game' },
    { id: 20, title: "All-Star Baseball 2005", Developers: "Acclaim Studios Austin", Publishers: "Acclaim Entertainment", Pal: "Unreleased", JP: "Unreleased", NA: "Mar 23, 2004", Genre: 'Sports game' },
    { id: 21, title: "Alter Echo", Developers: "Outrage Games", Publishers: "THQ", Pal: "Sep 12, 2003AUS Oct 3, 2003EU", JP: "Unreleased", NA: "Aug 18, 2003", Genre: 'Action-adventure' },
    { id: 22, title: "America's Army: Rise of a Soldier", Developers: "Secret Level, Inc.", Publishers: "Ubisoft", Pal: "Feb 24, 2006", JP: "Unreleased", NA: "Nov 15, 2005", Genre: 'FPS' },
    { id: 23, title: "American Chopper", Developers: "Creat Studios", Publishers: "Activision", Pal: "Nov 23, 2004", JP: "Unreleased", NA: "Nov 23, 2004", Genre: 'racing/simulation' },
    { id: 24, title: "American Chopper 2: Full Throttle", Developers: "Creat Studios", Publishers: "Activision", Pal: "Nov 16, 2005", JP: "Unreleased", NA: "Nov 16, 2005", Genre: 'racing/simulation' },
    { id: 25, title: "AMF Bowling 2004", Developers: "Black Market Games", Publishers: "Mud Duck Productions", Pal: "Unreleased", JP: "Unreleased", NA: "Dec 1, 2003", Genre: 'Bowling' },
    { id: 26, title: "AMF Xtreme Bowling", Developers: "Atomic Planet Entertainment", Publishers: "Mud Duck Productions", Pal: "Unreleased", JP: "Unreleased", NA: "Jun 28, 2006", Genre: 'Bowling' },
    { id: 27, title: "Amped: Freestyle Snowboarding", Developers: "Indie Built", Publishers: "Microsoft Game Studios", Pal: "Mar 14, 2002", JP: "Feb 22, 2002", NA: "Nov 20, 2001", Genre: 'Snowboarding' },
    { id: 28, title: "Amped 2", Developers: "Indie Built", Publishers: "Microsoft Game Studios", Pal: "Nov 14, 2003", JP: "Feb 26, 2004", NA: "Oct 28, 2003", Genre: 'Snowboarding' },
    { id: 29, title: "AND 1 Streetball", Developers: "Black Ops Entertainment", Publishers: "Ubisoft", Pal: "Aug 31, 2006AUS Sep 1, 2006EU", JP: "Unreleased", NA: "Jun 6, 2006", Genre: 'Sports, Basketball' },
    { id: 30, title: "Angelic Concert", Developers: "Success", Publishers: "Success", Pal: "Unreleased", JP: "Mar 13, 2003", NA: "Unreleased", Genre: 'Visual novel' },
    { id: 31, title: "Animaniacs: The Great Edgar Hunt", Developers: "Warthog Games", Publishers: "Ignition Entertainment", Pal: "Oct 14, 2005", JP: "Unreleased", NA: "Unreleased", Genre: 'Action-adventure' },
    { id: 32, title: "Antz Extreme Racing", Developers: "Supersonic Software", Publishers: "Empire Interactive", Pal: "Jul 26, 2002", JP: "Unreleased", NA: "Sep 5, 2002", Genre: 'Racing' },
    { id: 33, title: "Aoi Namida", Developers: "Artlim Media", Publishers: "Panther Software", Pal: "Unreleased", JP: "May 27, 2004", NA: "Unreleased", Genre: 'Visual novel' },
    { id: 34, title: "APEXRacing Evoluzione (PAL)", Developers: "Milestone", Publishers: "Infogrames", Pal: "Feb 28, 2003", JP: "Unreleased", NA: "Feb 18, 2003", Genre: 'Racing' },
    { id: 35, title: "Aquaman: Battle for Atlantis", Developers: "Lucky Chicken Games", Publishers: "TDK Mediactive", Pal: "Unreleased", JP: "Unreleased", NA: "Jul 30, 2003", Genre: 'Action-adventure' },
    { id: 36, title: "Arctic Thunder", Developers: "Inland Productions", Publishers: "Midway", Pal: "Mar 22, 2002", JP: "Unreleased", NA: "Nov 15, 2001", Genre: 'Racing' },
    { id: 37, title: "Area 51", Developers: "Midway Studios Austin", Publishers: "Midway", Pal: "May 26, 2005AUS May 27, 2005EU", JP: "Unreleased", NA: "Apr 25, 2005", Genre: 'First-person shooter' },
    { id: 38, title: "Arena Football", Developers: "EA Tiburon", Publishers: "EA Sports", Pal: "Unreleased", JP: "Unreleased", NA: "Feb 7, 2006", Genre: 'Sports' },
    { id: 39, title: "Armed and Dangerous", Developers: "Planet Moon Studios", Publishers: "LucasArts", Pal: "Feb 27, 2004", JP: "Unreleased", NA: "Dec 2, 2003", Genre: 'First-person shooter, third-person shooter' },
    { id: 40, title: "Army Men: Major Malfunction", Developers: "Team17", Publishers: "Global Star Software", Pal: "Aug 4, 2006", JP: "Unreleased", NA: "Apr 11, 2006", Genre: 'third-person shooter' },
    { id: 41, title: "Army Men: Sarge's War", Developers: "Tactical Development", Publishers: "Global Star Software", Pal: "Jul 23, 2004", JP: "Unreleased", NA: "Aug 2, 2004", Genre: 'third-person shooter' },
    { id: 42, title: "Arx Fatalis", Developers: "Wizarbox", Publishers: "DreamCatcher Interactive NA Mindscape PAL", Pal: "Feb 13, 2004UK", JP: "Unreleased", NA: "Dec 22, 2003", Genre: 'Action role-playing, dungeon craw' },
    { id: 43, title: "Atari Anthology", Developers: "Digital Eclipse", Publishers: "Atari Interactive", Pal: "Nov 26, 2004", JP: "Aug 4, 2005", NA: "Nov 16, 2004", Genre: 'Various' },
    { id: 44, title: "ATV: Quad Power Racing 2", Developers: "Climax Brighton", Publishers: "AKA Acclaim", Pal: "Feb 28, 2003", JP: "Unreleased", NA: "Jan 22, 2003", Genre: 'Racing' },
    { id: 45, title: "Auto Modellista", Developers: "Capcom Production Studio 1", Publishers: "Capcom", Pal: "Unreleased", JP: "Jan 29, 2004", NA: "Jan 20, 2004", Genre: 'Arcade style racing' },
    { id: 46, title: "Avatar: The Last Airbender", Developers: "THQ Studio Australia", Publishers: "THQ", Pal: "Unreleased", JP: "Unreleased", NA: "Oct 10, 2006", Genre: 'Action-adventure, action role-playing' },
    { id: 47, title: "Azurik: Rise of Perathia", Developers: "Adrenium Games", Publishers: "Microsoft Game Studios", Pal: "May 17, 2002", JP: "Unreleased", NA: "Nov 27, 2001", Genre: 'Action-adventure' },
    { id: 48, title: "Backyard Wrestling: Don't Try This at Home", Developers: "Paradox Development", Publishers: "Eidos Interactive", Pal: "Nov 7, 2003", JP: "Unreleased", NA: "Oct 9, 2003", Genre:'Fighting' },
    { id: 49, title: "Backyard Wrestling 2: There Goes the Neighborhood", Developers: "Paradox Development", Publishers: "Eidos Interactive", Pal: "Nov 19, 2004EU Dec 3, 2004AUS", JP: "Unreleased", NA: "Nov 16, 2004", Genre:'Fighting' },
    { id: 50, title: "Bad Boys: Miami TakedownBad Boys II (PAL)", Developers: "Blitz Games", Publishers: "Empire Interactive PAL Crave Entertainment NA", Pal: "Feb 27, 2004", JP: "Unreleased", NA: "Sep 21, 2004", Genre:'Action-adventure, Third-person shooter' },
    { id: 51, title: "Baldur's Gate: Dark Alliance", Developers: "Snowblind Studios", Publishers: "Interplay Entertainment", Pal: "Mar 21, 2003", JP: "Unreleased", NA: "Oct 22, 2002", Genre:'	Action role-playing, hack and slash' },
    { id: 52, title: "Baldur's Gate: Dark Alliance II", Developers: "Black Isle Studios", Publishers: "Interplay Entertainment", Pal: "Feb 6, 2004", JP: "Unreleased", NA: "Jan 20, 2004",  Genre:'	Action role-playing, hack and slash' },
    { id: 53, title: "Barbarian", Developers: "Saffire", Publishers: "Titus Interactive", Pal: "Dec 12, 2003", JP: "Unreleased", NA: "Unreleased", Genre:'Fighting game' },
    { id: 54, title: "Barbie Horse Adventures: Wild Horse Rescue", Developers: "Blitz Games", Publishers: "Vivendi Universal Games", Pal: "Feb 13, 2004", JP: "Unreleased", NA: "Nov 4, 2003", Genre:'Adventure, children, role-playing' },
    { id: 55, title: "The Bard's Tale", Developers: "InXile Entertainment", Publishers: "InXile Entertainment", Pal: "Mar 24, 2005", JP: "Unreleased", NA: "Oct 26, 2004", Genre:'Action role-playing' },
    { id: 56, title: "The Baseball 2002: Battle Ball Park Sengen", Developers: "Konami", Publishers: "Konami", Pal: "Unreleased", JP: "Jul 11, 2002", NA: "Unreleased", Genre:'Sports' },
    { id: 57, title: "Bass Pro Shops: Trophy Bass 2007", Developers: "Big John Games", Publishers: "Vivendi Universal Games", Pal: "Unreleased", JP: "Unreleased", NA: "Nov 20, 2006", Genre:'Sports' },
    { id: 58, title: "Bass Pro Shops Trophy Hunter 2007", Developers: "Jarhead Games", Publishers: "Vivendi Universal Games", Pal: "Unreleased", JP: "Unreleased", NA: "Nov 20, 2006", Genre:'Sports' },
    { id: 59, title: "Batman Begins", Developers: "Eurocom", Publishers: "EA Games Warner Bros. Interactive Entertainment", Pal: "Jun 17, 2005", JP: "Unreleased", NA: "Jun 15, 2005", Genre:'Action-adventure, Stealth' },
    { id: 60, title: "Batman: Dark Tomorrow", Developers: "HotGen", Publishers: "Kemco", Pal: "Apr 11, 2003", JP: "Mar 21, 2003", NA: "Mar 18, 2003", Genre:'Action-adventure, Stealth'  },
    { id: 61, title: "Batman: Rise of Sin Tzu", Developers: "Ubi Soft Montreal", Publishers: "Ubi Soft", Pal: "Nov 14, 2003", JP: "Unreleased", NA: "Oct 16, 2003", Genre:'Action-adventure, Stealth'  },
    { id: 62, title: "Batman: Vengeance", Developers: "Ubi Soft Montreal", Publishers: "Ubi Soft", Pal: "Mar 14, 2002", JP: "Unreleased", NA: "Dec 18, 2001", Genre:'Action-adventure, Stealth' },
    { id: 63, title: "Battle Engine Aquila", Developers: "Lost Toys", Publishers: "Infogrames", Pal: "Feb 28, 2003", JP: "Unreleased", NA: "Jan 27, 2003", Genre:'First-person shooter, simulation' },
    { id: 64, title: "Battlefield 2: Modern Combat", Developers: "DICE", Publishers: "Electronic Arts", Pal: "Nov 18, 2005", JP: "Unreleased", NA: "Oct 25, 2005", Genre:'First-person shooter' },
    { id: 65, title: "Battlestar Galactica", Developers: "Warthog Games", Publishers: "Universal Interactive", Pal: "Dec 5, 2003", JP: "Unreleased", NA: "Nov 18, 2003", Genre:'Space combat simulator' },
    { id: 66, title: "Beat Down: Fists of Vengeance", Developers: "Cavia", Publishers: "Capcom", Pal: "Sep 30, 2005", JP: "Nov 2, 2005", NA: "Aug 23, 2005", Genre:'Action role-playing, beatem up' },
    { id: 67, title: "Beyond Good & Evil", Developers: "Ubisoft Pictures Ubisoft Milan", Publishers: "Ubisoft", Pal: "Feb 27, 2004", JP: "Unreleased", NA: "Dec 2, 2003", Genre:'Action-adventure' },
    { id: 68, title: "The Bible Game", Developers: "Mass Media", Publishers: "Crave Entertainment", Pal: "Unreleased", JP: "Unreleased", NA: "Oct 18, 2005", Genre:'Christian, party' },
    { id: 69, title: "Bicycle Casino", Developers: "Leaping Lizard Software", Publishers: "Activision Value", Pal: "Mar 24, 2005", JP: "Unreleased", NA: "Oct 26, 2004", Genre:'Gambling' },
    { id: 70, title: "Big Bumpin", Developers: "Blitz Games", Publishers: "King Games", Pal: "Unreleased", JP: "Unreleased", NA: "Nov 19, 2006", Genre:'Racing, action' },
    { id: 71, title: "Big Mutha Truckers", Developers: "Eutechnyx", Publishers: "Empire Interactive PAL THQ NA", Pal: "Dec 6, 2002", JP: "Unreleased", NA: "Jun 23, 2003", Genre:'Racing' },
    { id: 72, title: "Big Mutha Truckers 2", Developers: "Eutechnyx", Publishers: "Empire Interactive PAL THQ NA", Pal: "Jun 24, 2005", JP: "Unreleased", NA: "Aug 23, 2005", Genre:'Racing' },
    { id: 73, title: "Bionicle", Developers: "Argonaut Games Argonaut Sheffield", Publishers: "Electronic Arts Lego Interactive", Pal: "Oct 17, 2003", JP: "Unreleased", NA: "Oct 20, 2003", Genre:'Platform' },
    { id: 74, title: "Bistro Cupid", Developers: "Success", Publishers: "Success", Pal: "Unreleased", JP: "Jun 13, 2002", NA: "Unreleased", Genre:'Role-playing game, simulation' },
    { id: 75, title: "Bistro Cupid 2", Developers: "Success", Publishers: "Success", Pal: "Unreleased", JP: "Aug 28, 2003", NA: "Unreleased", Genre:'Role-playing game, simulation' },
    { id: 76, title: "Black", Developers: "Criterion Games", Publishers: "Electronic Arts", Pal: "Feb 24, 2006", JP: "Unreleased", NA: "Feb 28, 2006", Genre:'First-person shooter' },
    { id: 77, title: "Black Stone: Magic & SteelEx-Chaser (JP)", Developers: "XPEC Entertainment", Publishers: "Xicat InteractiveWW Idea Factory JP", Pal: "Mar 21, 2003", JP: "May 22, 2003", NA: "Mar 13, 2003", Genre:'Action role-playing' },
    { id: 78, title: "Blade II", Developers: "Mucky Foot Productions", Publishers: "Activision", Pal: "Sep 27, 2002", JP: "Unreleased", NA: "Sep 3, 2002", Genre: "Action, beat 'em up" },
    { id: 79, title: "Blazing Angels: Squadrons of WWII", Developers: "Ubisoft Bucharest", Publishers: "Ubisoft", Pal: " Mar 31, 2006", JP: "Unreleased", NA: "Mar 23, 2006", Genre:'Flight combat'},
    { id: 80, title: "Blinx: The Time Sweeper", Developers: "Artoon", Publishers: "Microsoft Game Studios", Pal: "Nov 8, 2002EU", JP: "Dec 12, 2002", NA: "Oct 8, 2002", Genre:'Platform' },
    { id: 81, title: "Blinx 2: Masters of Time and Space", Developers: "Artoon", Publishers: "Microsoft Game Studios", Pal: "Dec 3, 2004", JP: "Nov 18, 2004", NA: "Nov 16, 2004", Genre:'Platform' },
    { id: 82, title: "Blitz: The League", Developers: "Midway Games", Publishers: "Midway", Pal: "Unreleased", JP: "Unreleased", NA: "Oct 17, 2005", Genre:'Sports' },
    { id: 83, title: "Blood Omen 2", Developers: "Nixxes Software", Publishers: "Eidos Interactive", Pal: "Mar 28, 2002", JP: "Unreleased", NA: "Mar 20, 2002", Genre:'Action-adventure' },
    { id: 84, title: "BloodRayne", Developers: "Terminal Reality", Publishers: "Majesco Sales NA Vivendi Universal Games PAL", Pal: "May 2, 2003", JP: "Unreleased", NA: "Oct 31, 2002", Genre:'Action, hack and slash' },
    { id: 85, title: "BloodRayne 2", Developers: "Terminal Reality", Publishers: "Majesco Sales", Pal: "Feb 17, 2006", JP: "Unreleased", NA: "Oct 12, 2004",  Genre:'Action, hack and slash'  },
    { id: 86, title: "Blood Wake", Developers: "Stormfront Studios", Publishers: "Microsoft Game Studios", Pal: "Mar 14, 2002", JP: "Unreleased", NA: "Dec 28, 2001", Genre:'Vehicle combat' },
    { id: 87, title: "Bloody Roar Extreme", Developers: "Konami Software Shanghai", Publishers: "Hudson Soft", Pal: "Jul 17, 2003", JP: "Nov 28, 2003", NA: "May 27, 2003", Genre:'Fighting' },
    { id: 88, title: "BlowOut", Developers: "Terminal Reality", Publishers: "Majesco Sales", Pal: "Nov 26, 2004", JP: "Unreleased", NA: "Nov 5, 2003", Genre:'Run and gun' },
    { id: 89, title: "BMX XXX", Developers: "Z-Axis", Publishers: "AKA Acclaim", Pal: "Dec 6, 2002", JP: "Unreleased", NA: "Nov 15, 2002", Genre:'Sports (freestyle BMX)' },
    { id: 90, title: "Braveknight", Developers: "Panther Software", Publishers: "Panther Software", Pal: "Unreleased", JP: "Sep 26, 2002", NA: "Unreleased", Genre:'Simulation' },
    { id: 91, title: "Break Nine: World Billiards Tournament", Developers: "ASK", Publishers: "ASK", Pal: "Unreleased", JP: "Jul 25, 2002", NA: "Unreleased", Genre:'Sports' },
    { id: 92, title: "Breakdown", Developers: "Namco", Publishers: "Namco", Pal: "Jun 18, 2004", JP: "Jan 29, 2004", NA: "Mar 16, 2004", Genre:'Action-adventure' },
    { id: 93, title: "Breeders' Cup World Thoroughbred Championships", Developers: "4J Studios", Publishers: "Bethesda Softworks", Pal: "Unreleased", JP: "Unreleased", NA: "Sep 21, 2005", Genre:'Horse racing' },
    { id: 94, title: "Brian Lara International Cricket 2005Ricky Ponting International Cricket 2005 (AUS)", Developers: "Swordfish Studios", Publishers: "Codemasters", Pal: "Jul 21, 2005EU Sep 29, 2005AUS", JP: "Unreleased", NA: "Unreleased", Genre:'Sports' },
    { id: 95, title: "Broken Sword: The Sleeping Dragon", Developers: "Revolution Software", Publishers: "THQ PAL The Adventure Company NA", Pal: "Nov 14, 2003", JP: "Unreleased", NA: "Dec 8, 2003", Genre:'Adventure' },
    { id: 96, title: "Brothers in Arms: Earned in Blood", Developers: "Gearbox Software", Publishers: "Ubisoft", Pal: "Oct 6, 2005AUS Oct 7, 2005EU", JP: "Unreleased", NA: "Oct 6, 2005", Genre:'	First-person shooter' },
    { id: 97, title: "Brothers in Arms: Road to Hill 30", Developers: "Gearbox Software", Publishers: "Ubisoft", Pal: "Mar 18, 2005", JP: "Sep 15, 2005", NA: "Mar 1, 2005", Genre:'First-person shooter' },
    { id: 98, title: "Bruce Lee: Quest of the Dragon", Developers: "Ronin Entertainment", Publishers: "Universal Interactive", Pal: "Sep 6, 2002", JP: "Unreleased", NA: "Jul 2, 2002", Genre:"Beat 'em up" },
    { id: 99, title: "Brute Force", Developers: "Digital Anvil", Publishers: "Microsoft Game Studios", Pal: "Jun 5, 2003AUS Jun 20, 2003EU", JP: "Oct 9, 2003", NA: "May 27, 2003", Genre:'Third-person shooter Tactical shooter' },
    { id: 100, title: "Buffy the Vampire Slayer", Developers: "The Collective", Publishers: "Electronic Arts", Pal: "Sep 13, 2002", JP: "Unreleased", NA: "Aug 19, 2002", Genre:"Action-adventure, beat 'em up"},
    { id: 101, title: "Buffy the Vampire Slayer: Chaos Bleeds", Developers: "Eurocom", Publishers: "Vivendi Universal Games", Pal: "Oct 24, 2003EU Oct 29, 2003AUS", JP: "Dec 25, 2003", NA: "August 26, 2003", Genre:"Action-adventure, beat 'em up" },
    { id: 102, title: "Burnout", Developers: "Criterion Games", Publishers: "Acclaim Entertainment", Pal: "May 3, 2002", JP: "Unreleased", NA: "Apr 30, 2002", Genre:'Racing' },
    { id: 103, title: "Burnout 2: Point of Impact", Developers: "Criterion Games", Publishers: "Acclaim Entertainment", Pal: "May 9, 2003EU May 15, 2003AUS", JP: "Unreleased", NA: "May 1, 2003",  Genre:'Racing' },
    { id: 104, title: "Burnout 3: Takedown", Developers: "Criterion Games", Publishers: "EA Games", Pal: "Sep 9, 2004AUS Sep 10, 2004EU", JP: "Unreleased", NA: "Sep 8, 2004", Genre:'Racing'  },
    { id: 105, title: "Burnout Revenge", Developers: "Criterion Games", Publishers: "Electronic Arts", Pal: "Sep 23, 2005EU Sep 26, 2005AUS", JP: "Unreleased", NA: "Sep 13, 2005", Genre:'Racing'},
    { id: 106, title: "C.A.T.: Cyber Attack Team", Developers: "Hyde Medix", Publishers: "Medix", Pal: "Unreleased", JP: "Jun 26, 2003", NA: "Unreleased", Genre:'	Turn-based tactics'},
    { id: 107, title: "Cabela's Big Game Hunter 2005 Adventures", Developers: "Fun Labs", Publishers: "Activision", Pal: "Oct 14, 2005", JP: "Unreleased", NA: "Nov 23, 2004", Genre:'First-person shooter, sports' },
    { id: 108, title: "Cabela's Dangerous Hunts", Developers: "Fun Labs", Publishers: "Activision", Pal: "Oct 1, 2004", JP: "Unreleased", NA: "Nov 11, 2003",  Genre:'First-person shooter, sports'  },
    { id: 109, title: "Cabela's Dangerous Hunts 2", Developers: "Fun Labs", Publishers: "Activision", Pal: "Mar 1, 2006", JP: "Unreleased", NA: "Nov 15, 2005", Genre:'First-person shooter, sports'  },
    { id: 110, title: "Cabela's Deer Hunt: 2004 Season", Developers: "Fun Labs", Publishers: "Activision", Pal: "Unreleased", JP: "Unreleased", NA: "Aug 26, 2003", Genre:'First-person shooter, sports'  },
    { id: 111, title: "Cabela's Deer Hunt: 2005 Season", Developers: "Fun Labs", Publishers: "Activision", Pal: "Feb 2, 2005", JP: "Unreleased", NA: "Aug 31, 2004" , Genre:'First-person shooter, sports'  },
    { id: 112, title: "Cabela's Outdoor Adventures", Developers: "Fun Labs", Publishers: "Activision", Pal: "Mar 17, 2006", JP: "Unreleased", NA: "Sep 14, 2005", Genre:'First-person shooter, sports' },
    { id: 113, title: "Call of Cthulhu: Dark Corners of the Earth", Developers: "Headfirst Productions", Publishers: "2K Games", Pal: "Oct 28, 2005", JP: "Unreleased", NA: "Oct 24, 2005", Genre:'Survival horror' },
    { id: 114, title: "Call of Duty: Finest Hour", Developers: "Spark Unlimited Kuju Entertainment", Publishers: "Activision", Pal: "Nov 25, 2004AUS Dec 3, 2004EU", JP: "Oct 27, 2005", NA: "Nov 16, 2004", Genre:'First-person shooter' },
    { id: 115, title: "Call of Duty 2: Big Red One", Developers: "Treyarch", Publishers: "Activision", Pal: "Nov 18, 2005", JP: "Unreleased", NA: "Nov 1, 2005",Genre:'First-person shooter' },
    { id: 116, title: "Call of Duty 3", Developers: "Treyarch", Publishers: "Activision", Pal: "Nov 10, 2006EU Nov 22, 2006AUS", JP: "Unreleased", NA: "Nov 7, 2006", Genre:'First-person shooter' },
    { id: 117, title: "Capcom Classics Collection Vol. 1", Developers: "Backbone Entertainment", Publishers: "Capcom", Pal: "Nov 18, 2005", JP: "Unreleased", NA: "Sep 27, 2005", Genre:'Various'},
    { id: 118, title: "Capcom Classics Collection Vol. 2", Developers: "Backbone Entertainment", Publishers: "Capcom", Pal: "Unreleased", JP: "Unreleased", NA: "Nov 14, 2006", Genre:'Various'},
    { id: 119, title: "Capcom Fighting EvolutionCapcom Fighting Jam (JP/PAL)", Developers: "Capcom Production Studio 2", Publishers: "Capcom", Pal: "Jun 24, 2005", JP: "Jun 16, 2005", NA: "Jun 14, 2005", Genre:'Fighting' },
    { id: 120, title: "Capcom vs. SNK 2 EO", Developers: "Capcom", Publishers: "Capcom", Pal: "Mar 7, 2003", JP: "Jan 16, 2003", NA: "Feb 11, 2003", Genre:'Fighting'},
    { id: 121, title: "Carmen Sandiego: The Secret of the Stolen Drums", Developers: "Artificial Mind and Movement", Publishers: "BAM! Entertainment", Pal: "Mar 5, 2004", JP: "Unreleased", NA: "Sep 13, 2004",Genre:'Action-adventure, platformer' },
    { id: 122, title: "Cars", Developers: "Rainbow Studios", Publishers: "THQ", Pal: "Jun 8, 2006AUS Jul 14, 2006EU", JP: "Unreleased", NA: "Jun 6, 2006", Genre:'Adventure, racing' },
    { id: 123, title: "Carve", Developers: "Argonaut Games", Publishers: "Global Star Software", Pal: "Mar 19, 2004", JP: "Unreleased", NA: "Feb 24, 2004", Genre:'Racing' },
    { id: 124, title: "Castlevania: Curse of Darkness", Developers: "Konami", Publishers: "Konami", Pal: "Feb 17, 2006", JP: "Unreleased", NA: "Nov 1, 2005", Genre:'Action role-playing, hack and slash'},
];

app.get('/games', (req, res) => {
    res.send(games);
});

//Using the /id so if it will just use 2 or 3 ect 
app.get('/games/:id', (req, res) => {
    const parsedganesId = parseInt(req.params.id);
    if (isNaN(parsedganesId)) {
        return res.status(404).send({ msg: 'Bad REquest. Invalid ID.' });
    }
    const findGamesID = games.find(g => g.id === parsedganesId);
    if (!findGamesID) {
        return res.sendStatus(404);
    }
    res.send(findGamesID);
})
module.exports = app;